name: meme_baaz
description: Daily Meme Updates.

publish_to: "none"
version: 1.2.0+120

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  animations: ^2.0.3
  cached_network_image: ^3.2.1
  cached_video_player: ^2.0.3
  cloud_firestore: ^3.4.4
  connectivity: ^3.0.6
  cupertino_icons: ^1.0.5
  dio: ^4.0.0
  firebase_auth: ^3.6.3
  firebase_core: ^1.20.1
  firebase_messaging: ^12.0.2
  firebase_storage: ^10.3.5
  flare_flutter: ^3.0.2
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.3.0
  flutter_form_builder: ^7.5.0
  flutter_image_compress: ^1.1.1
  flutter_launcher_icons: ^0.10.0
  flutter_native_splash: ^2.2.7
  flutter_svg: ^1.1.3
  fluttertoast: ^8.0.9
  font_awesome_flutter: ^10.1.0
  get: ^4.6.5
  get_storage: ^2.0.3
  google_fonts: ^3.0.1
  image_gallery_saver: ^1.7.1
  lazy_load_scrollview: ^1.3.0
  like_button: ^2.0.4
  line_icons: ^2.0.1
  modal_bottom_sheet: ^2.1.0
  octo_image: ^1.0.2
  preload_page_view: ^0.1.6
  readmore: ^2.2.0
  shimmer: ^2.0.0
  timeago: ^3.3.0
  url_launcher: ^6.1.5
  visibility_detector: ^0.3.3
  wc_flutter_share: ^0.4.0
  wechat_assets_picker: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.5.3
  pedantic: ^1.11.0

flutter_native_splash:
  image: assets/splash.png
  color: "FFFFFF"

flutter:
  uses-material-design: true
  assets:
    - assets/
